name: Update Version Info Gist

on:
  release:
    types: [published]

jobs:
  update-gist:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install J81.PSScriptTools Module
        shell: pwsh
        run: |
          #Install-Module -Name J81.PSScriptTools -Scope CurrentUser -Force -AllowClobber -ErrorAction Stop
          iex (irm https://raw.githubusercontent.com/j81blog/J81.PSScriptTools/refs/heads/dev/Install-ModuleFromGithubDev.ps1)

      - name: Determine Version and Channel
        id: vars
        shell: pwsh
        working-directory: ${{ github.workspace }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            $params = @{
                GithubRepository = "${{ github.repository }}"
                GithubEventReleaseTagName = "${{ github.event.release.tag_name }}"
            }
            ./.github/scripts/Get-VersionAndChannel.ps1 @params


      - name: Update Gist Content
        shell: pwsh
        working-directory: ${{ github.workspace }}
        env:
          PAT_TOKEN: ${{ secrets.GIST_PAT }}
        run: |
            $params = @{
                GithubRepository = "${{ github.repository }}"
                GithubGistID = "${{ vars.GIST_ID }}"
                GithubGistFilename = "${{ vars.GIST_FILE }}"
                Version = "${{ steps.vars.outputs.version }}"
                Channel = "${{ steps.vars.outputs.channel }}"
            }
            ./.github/scripts/Set-GistContent.ps1 @params

      - name: Test Gist Update
        shell: pwsh
        working-directory: ${{ github.workspace }}
        env:
          PAT_TOKEN: ${{ secrets.GIST_PAT }}
        run: |
          $params = @{
              GithubGistID = "${{ vars.GIST_ID }}"
              GithubGistFilename = "${{ vars.GIST_FILE }}"
              Version = "${{ steps.vars.outputs.version }}"
              Channel = "${{ steps.vars.outputs.channel }}"
          }
          ./.github/scripts/Test-GistUpdate.ps1 @params
